---
classes:
  - exercises:
      - file: "../codelab/lab1.md"
        title: "Lab 1 : Mettre en place le Mutation Testing"
        syntax: "md-extended"
      - file: "../codelab/lab2.md"
        title: "Lab 2 : FizzBuzz"
        syntax: "md-extended"
      - file: "../codelab/lab3.md"
        title: "Lab 3 : Pile"
        syntax: "md-extended"
      - file: "../codelab/lab4.md"
        title: "Lab 4 : Spring"
        syntax: "md-extended"
      - file: "../codelab/lab5.md"
        title: "Lab 5 : Bonus Trie à bulles"
        syntax: "md-extended"